
package restaurant.ui;

import java.awt.Color;
import javax.swing.border.Border;
import restaurant.businesslogic.CategoryNode;

/**
 *
 * @author Shaswat
 */
public class CategoryUI extends javax.swing.JDialog {

    Restaurant restaurant;

    String name;

    /**
     * Creates new form Category
     */
    public CategoryUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Creates new form Category
     */
    public CategoryUI(Restaurant parent, boolean modal) {
        this(null, parent, modal);
    }

    /**
     * Creates new form Category
     */
    public CategoryUI(String name, Restaurant parent, boolean modal) {
        super(parent, modal);
        this.name = name;
        this.restaurant = parent;
        initComponents();
        if (this.name != null) {
            jTextFieldName.setText(name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelDescription = new javax.swing.JLabel();
    jLabelDescription1 = new javax.swing.JLabel();
    jTextFieldName = new javax.swing.JTextField();
    jButtonCancel = new javax.swing.JButton();
    jButtonOK = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(237, 107));

    jLabelDescription.setText("Please enter the category name");

    jLabelDescription1.setText("Name");

    jButtonCancel.setText("Cancel");

    jButtonOK.setText("OK");
    jButtonOK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonOKActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelDescription)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(4, 4, 4)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancel))
              .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabelDescription)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelDescription1)
          .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButtonCancel)
          .addComponent(jButtonOK))
        .addContainerGap(18, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
      if (jTextFieldName.getText().trim().equals("")) {
          jTextFieldName.setBackground(Color.yellow);
          return;
      }
      if (name != null) {
          restaurant.updateCategoryNode(name, jTextFieldName.getText());
      } else {
          restaurant.setCurrentCategoryNode(new CategoryNode(jTextFieldName.getText()));
      }
      this.setVisible(false);
  }//GEN-LAST:event_jButtonOKActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonCancel;
  private javax.swing.JButton jButtonOK;
  private javax.swing.JLabel jLabelDescription;
  private javax.swing.JLabel jLabelDescription1;
  private javax.swing.JTextField jTextFieldName;
  // End of variables declaration//GEN-END:variables
}
