
package restaurant.ui;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import restaurant.businesslogic.CategoryList;
import restaurant.businesslogic.CategoryNode;
import restaurant.businesslogic.FoodItem;
import restaurant.businesslogic.LinkedList;

/**
 *
 * @author Shaswat
 */
public class Restaurant extends javax.swing.JFrame {

    CategoryList categories;

    FoodItem currentFoodItem;

    CategoryNode currentCategoryNode;

    DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
        categories = new CategoryList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSearch = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableItems = new javax.swing.JTable();
        jButtonUpdateFoodItem = new javax.swing.JButton();
        jButtonDeleteFoodItem = new javax.swing.JButton();
        jTextFieldSearchFoodItem = new javax.swing.JTextField();
        jLabelSearch = new javax.swing.JLabel();
        jButtonSearchFoodItem = new javax.swing.JButton();
        jButtonAddFoodItemForm = new javax.swing.JButton();
        jButtonAddFoodItemFile = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldSearchCategory = new javax.swing.JTextField();
        jLabelSearchCategory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCategories = new javax.swing.JList();
        jButtonSearchCategory = new javax.swing.JButton();
        jButtonUpdateCategory = new javax.swing.JButton();
        jButtonDeleteCategory = new javax.swing.JButton();
        jButtonAddCategory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(503, 585));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Food Items"));

        jTableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableItems);

        jButtonUpdateFoodItem.setText("Update");

        jButtonDeleteFoodItem.setText("Delete");

        jLabelSearch.setText("Search");

        jButtonSearchFoodItem.setText("Search");

        jButtonAddFoodItemForm.setText("Add (Form)");
        jButtonAddFoodItemForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddFoodItemFormActionPerformed(evt);
            }
        });

        jButtonAddFoodItemFile.setText("Add (File)");

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSearchLayout.createSequentialGroup()
                        .addComponent(jLabelSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSearchFoodItem))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUpdateFoodItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSearchFoodItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddFoodItemForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddFoodItemFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteFoodItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchLayout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchFoodItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearch)
                    .addComponent(jButtonSearchFoodItem))
                .addGap(12, 12, 12)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addComponent(jButtonAddFoodItemForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAddFoodItemFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUpdateFoodItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteFoodItem))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonClose.setText("Close");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Category"));

        jLabelSearchCategory.setText("Search");

        jListCategories.setModel(listModel);
        jListCategories.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCategoriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListCategories);

        jButtonSearchCategory.setText("Search");
        jButtonSearchCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCategoryActionPerformed(evt);
            }
        });

        jButtonUpdateCategory.setText("Update");
        jButtonUpdateCategory.setEnabled(false);
        jButtonUpdateCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateCategoryActionPerformed(evt);
            }
        });

        jButtonDeleteCategory.setText("Delete");
        jButtonDeleteCategory.setEnabled(false);
        jButtonDeleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCategoryActionPerformed(evt);
            }
        });

        jButtonAddCategory.setText("Add");
        jButtonAddCategory.setToolTipText("");
        jButtonAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSearchCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtonSearchCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUpdateCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchCategory)
                    .addComponent(jButtonSearchCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                        .addComponent(jButtonAddCategory)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateCategory)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteCategory)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonClose))
                    .addComponent(jPanelSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClose)
                .addContainerGap())
        );

        jPanelSearch.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jButtonAddFoodItemFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddFoodItemFormActionPerformed
      
  }//GEN-LAST:event_jButtonAddFoodItemFormActionPerformed

  private void jButtonAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCategoryActionPerformed
      CategoryUI cUI = new CategoryUI(this, rootPaneCheckingEnabled);
      setLocationRelativeTo(this);
      cUI.setVisible(true);
      if (currentCategoryNode != null) {
          categories.add(currentCategoryNode);
          rebuildCategoryList();
      }
  }//GEN-LAST:event_jButtonAddCategoryActionPerformed

    private void jButtonUpdateCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateCategoryActionPerformed
        CategoryUI cUI = new CategoryUI(jListCategories.getSelectedValue().toString(), this, rootPaneCheckingEnabled);
        setLocationRelativeTo(this);
        cUI.setVisible(true);
    }//GEN-LAST:event_jButtonUpdateCategoryActionPerformed

    private void jListCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCategoriesValueChanged
        boolean enable = jListCategories.getSelectedIndex() >= 0;
        jButtonUpdateCategory.setEnabled(enable);
        jButtonDeleteCategory.setEnabled(enable);
    }//GEN-LAST:event_jListCategoriesValueChanged

    private void jButtonDeleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCategoryActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this category. "
                + "This will delete all food items related to this.", "Restaurant", JOptionPane.YES_NO_CANCEL_OPTION);
        if (JOptionPane.YES_OPTION == confirm) {
            categories.deleteByName(jListCategories.getSelectedValue().toString());
            rebuildCategoryList();
        }
    }//GEN-LAST:event_jButtonDeleteCategoryActionPerformed

    private void jButtonSearchCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCategoryActionPerformed
        if (jTextFieldSearchCategory.getText().isEmpty()) {
            rebuildCategoryList();
            return;
        }
        LinkedList<CategoryNode> result = categories.search(jTextFieldSearchCategory.getText().trim());
        listModel.clear();
        for (CategoryNode c : result) {
            listModel.addElement(c.getName());
        }
    }//GEN-LAST:event_jButtonSearchCategoryActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirm = JOptionPane.showConfirmDialog(this, "Do you want to exit for sure?", "Restaurant", JOptionPane.YES_NO_CANCEL_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            setVisible(false);
        } else {

        }
    }//GEN-LAST:event_formWindowClosing

    public void setCurrentCategoryNode(CategoryNode c) {
        currentCategoryNode = c;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCategory;
    private javax.swing.JButton jButtonAddFoodItemFile;
    private javax.swing.JButton jButtonAddFoodItemForm;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDeleteCategory;
    private javax.swing.JButton jButtonDeleteFoodItem;
    private javax.swing.JButton jButtonSearchCategory;
    private javax.swing.JButton jButtonSearchFoodItem;
    private javax.swing.JButton jButtonUpdateCategory;
    private javax.swing.JButton jButtonUpdateFoodItem;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelSearchCategory;
    private javax.swing.JList jListCategories;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableItems;
    private javax.swing.JTextField jTextFieldSearchCategory;
    private javax.swing.JTextField jTextFieldSearchFoodItem;
    // End of variables declaration//GEN-END:variables

    void updateCategoryNode(String oldName, String newName) {
        categories.updateByName(oldName, newName);
        if (currentCategoryNode != null) {
            rebuildCategoryList();
        }
    }

    private void rebuildCategoryList() {
        listModel.clear();
        for (CategoryNode c : categories.getCategories()) {
            listModel.addElement(c.getName());
        }
    }
}
